author = "tonyfast"
comments_config = {"hypothesis": True, "utterances": False}
copyright = "2020"
exclude_patterns = [
    "**.ipynb_checkpoints",
    ".DS_Store",
    ".benchmarks/*",
    ".hypothesis/*",
    ".ipynb_checkpoints/*",
    ".pytest_cache/*",
    ".vscode/*",
    "Thumbs.db",
    "__pycache__/*",
    "__pycache__/conftest.cpython-37-pytest-6.2.0.pyc",
    "__pycache__/conftest.cpython-37-pytest-6.2.3.pyc",
    "__pycache__/dodo.cpython-37.pyc",
    "__pycache__/noxfile.cpython-37.pyc",
    "_build",
    "_build/_panels_static/panels-main.c949a650a448cc0ae9fd3441c0e17fb0.css",
    "_build/_panels_static/panels-variables.06eb56fa6e07937060861dad626602ad.css",
    "_build/_sources/docs/extras/ipython-extension.ipynb",
    "_build/_sources/docs/schemata-types.ipynb",
    "_build/_sources/readme.md",
    "_build/_static/__init__.py",
    "_build/_static/__pycache__/__init__.cpython-37.pyc",
    "_build/_static/basic.css",
    "_build/_static/clipboard.min.js",
    "_build/_static/copy-button.svg",
    "_build/_static/copybutton.css",
    "_build/_static/copybutton.js",
    "_build/_static/copybutton_funcs.js",
    "_build/_static/css/index.73d71520a4ca3b99cfee5594769eaaae.css",
    "_build/_static/doctools.js",
    "_build/_static/documentation_options.js",
    "_build/_static/file.png",
    "_build/_static/images/logo_binder.svg",
    "_build/_static/images/logo_colab.png",
    "_build/_static/images/logo_jupyterhub.svg",
    "_build/_static/jquery-3.5.1.js",
    "_build/_static/jquery.js",
    "_build/_static/js/index.3da636dd464baa7582d2.js",
    "_build/_static/language_data.js",
    "_build/_static/minus.png",
    "_build/_static/mystnb.css",
    "_build/_static/panels-main.c949a650a448cc0ae9fd3441c0e17fb0.css",
    "_build/_static/panels-variables.06eb56fa6e07937060861dad626602ad.css",
    "_build/_static/plus.png",
    "_build/_static/pygments.css",
    "_build/_static/searchtools.js",
    "_build/_static/sphinx-book-theme.40e2e510f6b7d1648584402491bb10fe.css",
    "_build/_static/sphinx-book-theme.css",
    "_build/_static/sphinx-book-theme.d31b09fe5c1d09cb49b26a786de4a05d.js",
    "_build/_static/sphinx-thebe.css",
    "_build/_static/sphinx-thebe.js",
    "_build/_static/togglebutton.css",
    "_build/_static/togglebutton.js",
    "_build/_static/underscore-1.3.1.js",
    "_build/_static/underscore.js",
    "_build/_static/vendor/fontawesome/5.13.0/LICENSE.txt",
    "_build/_static/vendor/fontawesome/5.13.0/css/all.min.css",
    "_build/_static/vendor/fontawesome/5.13.0/webfonts/fa-brands-400.eot",
    "_build/_static/vendor/fontawesome/5.13.0/webfonts/fa-brands-400.svg",
    "_build/_static/vendor/fontawesome/5.13.0/webfonts/fa-brands-400.ttf",
    "_build/_static/vendor/fontawesome/5.13.0/webfonts/fa-brands-400.woff",
    "_build/_static/vendor/fontawesome/5.13.0/webfonts/fa-brands-400.woff2",
    "_build/_static/vendor/fontawesome/5.13.0/webfonts/fa-regular-400.eot",
    "_build/_static/vendor/fontawesome/5.13.0/webfonts/fa-regular-400.svg",
    "_build/_static/vendor/fontawesome/5.13.0/webfonts/fa-regular-400.ttf",
    "_build/_static/vendor/fontawesome/5.13.0/webfonts/fa-regular-400.woff",
    "_build/_static/vendor/fontawesome/5.13.0/webfonts/fa-regular-400.woff2",
    "_build/_static/vendor/fontawesome/5.13.0/webfonts/fa-solid-900.eot",
    "_build/_static/vendor/fontawesome/5.13.0/webfonts/fa-solid-900.svg",
    "_build/_static/vendor/fontawesome/5.13.0/webfonts/fa-solid-900.ttf",
    "_build/_static/vendor/fontawesome/5.13.0/webfonts/fa-solid-900.woff",
    "_build/_static/vendor/fontawesome/5.13.0/webfonts/fa-solid-900.woff2",
    "_build/_static/vendor/lato_latin-ext/1.44.1/LICENSE.md",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-100-italic.woff",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-100-italic.woff2",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-100.woff",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-100.woff2",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-300-italic.woff",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-300-italic.woff2",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-300.woff",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-300.woff2",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-400-italic.woff",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-400-italic.woff2",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-400.woff",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-400.woff2",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-700-italic.woff",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-700-italic.woff2",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-700.woff",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-700.woff2",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-900-italic.woff",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-900-italic.woff2",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-900.woff",
    "_build/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-900.woff2",
    "_build/_static/vendor/lato_latin-ext/1.44.1/index.css",
    "_build/_static/vendor/open-sans_all/1.44.1/LICENSE.md",
    "_build/_static/vendor/open-sans_all/1.44.1/files/open-sans-all-400-italic.woff",
    "_build/_static/vendor/open-sans_all/1.44.1/files/open-sans-all-400-italic.woff2",
    "_build/_static/vendor/open-sans_all/1.44.1/files/open-sans-all-400.woff",
    "_build/_static/vendor/open-sans_all/1.44.1/files/open-sans-all-400.woff2",
    "_build/_static/vendor/open-sans_all/1.44.1/index.css",
    "_build/_static/webpack-macros.html",
    "_build/docs/extras/ipython-extension.html",
    "_build/docs/schemata-types.html",
    "_build/genindex.html",
    "_build/html/_panels_static/panels-main.c949a650a448cc0ae9fd3441c0e17fb0.css",
    "_build/html/_panels_static/panels-variables.06eb56fa6e07937060861dad626602ad.css",
    "_build/html/_sources/docs/comparison.md",
    "_build/html/_sources/docs/extras/ipython-extension.ipynb",
    "_build/html/_sources/docs/readme.ipynb",
    "_build/html/_sources/docs/schemata-types.ipynb",
    "_build/html/_sources/readme.md",
    "_build/html/_static/__init__.py",
    "_build/html/_static/__pycache__/__init__.cpython-37.pyc",
    "_build/html/_static/basic.css",
    "_build/html/_static/clipboard.min.js",
    "_build/html/_static/copy-button.svg",
    "_build/html/_static/copybutton.css",
    "_build/html/_static/copybutton.js",
    "_build/html/_static/copybutton_funcs.js",
    "_build/html/_static/css/index.73d71520a4ca3b99cfee5594769eaaae.css",
    "_build/html/_static/doctools.js",
    "_build/html/_static/documentation_options.js",
    "_build/html/_static/file.png",
    "_build/html/_static/images/logo_binder.svg",
    "_build/html/_static/images/logo_colab.png",
    "_build/html/_static/images/logo_jupyterhub.svg",
    "_build/html/_static/jquery-3.5.1.js",
    "_build/html/_static/jquery.js",
    "_build/html/_static/js/index.3da636dd464baa7582d2.js",
    "_build/html/_static/language_data.js",
    "_build/html/_static/minus.png",
    "_build/html/_static/mystnb.css",
    "_build/html/_static/panels-main.c949a650a448cc0ae9fd3441c0e17fb0.css",
    "_build/html/_static/panels-variables.06eb56fa6e07937060861dad626602ad.css",
    "_build/html/_static/plus.png",
    "_build/html/_static/pygments.css",
    "_build/html/_static/searchtools.js",
    "_build/html/_static/sphinx-book-theme.40e2e510f6b7d1648584402491bb10fe.css",
    "_build/html/_static/sphinx-book-theme.css",
    "_build/html/_static/sphinx-book-theme.d31b09fe5c1d09cb49b26a786de4a05d.js",
    "_build/html/_static/sphinx-thebe.css",
    "_build/html/_static/sphinx-thebe.js",
    "_build/html/_static/togglebutton.css",
    "_build/html/_static/togglebutton.js",
    "_build/html/_static/underscore-1.3.1.js",
    "_build/html/_static/underscore.js",
    "_build/html/_static/vendor/fontawesome/5.13.0/LICENSE.txt",
    "_build/html/_static/vendor/fontawesome/5.13.0/css/all.min.css",
    "_build/html/_static/vendor/fontawesome/5.13.0/webfonts/fa-brands-400.eot",
    "_build/html/_static/vendor/fontawesome/5.13.0/webfonts/fa-brands-400.svg",
    "_build/html/_static/vendor/fontawesome/5.13.0/webfonts/fa-brands-400.ttf",
    "_build/html/_static/vendor/fontawesome/5.13.0/webfonts/fa-brands-400.woff",
    "_build/html/_static/vendor/fontawesome/5.13.0/webfonts/fa-brands-400.woff2",
    "_build/html/_static/vendor/fontawesome/5.13.0/webfonts/fa-regular-400.eot",
    "_build/html/_static/vendor/fontawesome/5.13.0/webfonts/fa-regular-400.svg",
    "_build/html/_static/vendor/fontawesome/5.13.0/webfonts/fa-regular-400.ttf",
    "_build/html/_static/vendor/fontawesome/5.13.0/webfonts/fa-regular-400.woff",
    "_build/html/_static/vendor/fontawesome/5.13.0/webfonts/fa-regular-400.woff2",
    "_build/html/_static/vendor/fontawesome/5.13.0/webfonts/fa-solid-900.eot",
    "_build/html/_static/vendor/fontawesome/5.13.0/webfonts/fa-solid-900.svg",
    "_build/html/_static/vendor/fontawesome/5.13.0/webfonts/fa-solid-900.ttf",
    "_build/html/_static/vendor/fontawesome/5.13.0/webfonts/fa-solid-900.woff",
    "_build/html/_static/vendor/fontawesome/5.13.0/webfonts/fa-solid-900.woff2",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/LICENSE.md",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-100-italic.woff",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-100-italic.woff2",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-100.woff",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-100.woff2",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-300-italic.woff",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-300-italic.woff2",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-300.woff",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-300.woff2",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-400-italic.woff",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-400-italic.woff2",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-400.woff",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-400.woff2",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-700-italic.woff",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-700-italic.woff2",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-700.woff",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-700.woff2",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-900-italic.woff",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-900-italic.woff2",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-900.woff",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/files/lato-latin-ext-900.woff2",
    "_build/html/_static/vendor/lato_latin-ext/1.44.1/index.css",
    "_build/html/_static/vendor/open-sans_all/1.44.1/LICENSE.md",
    "_build/html/_static/vendor/open-sans_all/1.44.1/files/open-sans-all-400-italic.woff",
    "_build/html/_static/vendor/open-sans_all/1.44.1/files/open-sans-all-400-italic.woff2",
    "_build/html/_static/vendor/open-sans_all/1.44.1/files/open-sans-all-400.woff",
    "_build/html/_static/vendor/open-sans_all/1.44.1/files/open-sans-all-400.woff2",
    "_build/html/_static/vendor/open-sans_all/1.44.1/index.css",
    "_build/html/_static/webpack-macros.html",
    "_build/html/docs/comparison.html",
    "_build/html/docs/extras/ipython-extension.html",
    "_build/html/docs/readme.html",
    "_build/html/docs/schemata-types.html",
    "_build/html/genindex.html",
    "_build/html/index.html",
    "_build/html/objects.inv",
    "_build/html/readme.html",
    "_build/html/search.html",
    "_build/html/searchindex.js",
    "_build/jupyter_execute/docs/extras/ipython-extension.ipynb",
    "_build/jupyter_execute/docs/extras/ipython-extension.py",
    "_build/jupyter_execute/docs/readme.ipynb",
    "_build/jupyter_execute/docs/readme.py",
    "_build/jupyter_execute/docs/schemata-types.ipynb",
    "_build/jupyter_execute/docs/schemata-types.py",
    "_build/latex/LICRcyr2utf8.xdy",
    "_build/latex/LICRlatin2utf8.xdy",
    "_build/latex/LatinRules.xdy",
    "_build/latex/Makefile",
    "_build/latex/_panels_static/panels-main.c949a650a448cc0ae9fd3441c0e17fb0.css",
    "_build/latex/_panels_static/panels-variables.06eb56fa6e07937060861dad626602ad.css",
    "_build/latex/footnotehyper-sphinx.sty",
    "_build/latex/index.html",
    "_build/latex/latexmkjarc",
    "_build/latex/latexmkrc",
    "_build/latex/make.bat",
    "_build/latex/python.aux",
    "_build/latex/python.fdb_latexmk",
    "_build/latex/python.fls",
    "_build/latex/python.idx",
    "_build/latex/python.ist",
    "_build/latex/python.log",
    "_build/latex/python.out",
    "_build/latex/python.pdf",
    "_build/latex/python.tex",
    "_build/latex/python.toc",
    "_build/latex/sphinx.sty",
    "_build/latex/sphinx.xdy",
    "_build/latex/sphinxcyrillic.sty",
    "_build/latex/sphinxhighlight.sty",
    "_build/latex/sphinxhowto.cls",
    "_build/latex/sphinxmanual.cls",
    "_build/latex/sphinxmessages.sty",
    "_build/latex/sphinxmulticell.sty",
    "_build/objects.inv",
    "_build/readme.html",
    "_build/search.html",
    "_build/searchindex.js",
    "conf.py",
    "conftest.py",
    "dist/SHA256SUMS",
    "dist/schemata-0.0.1-py3-none-any.whl",
    "dist/schemata-0.0.1.tar.gz",
    "docs/.hypothesis/*",
    "docs/.ipynb_checkpoints/*",
    "docs/__pycache__/*",
    "docs/__pycache__/ipython-extension.cpython-37.pyc",
    "docs/__pycache__/test_jsonschemata.cpython-37.pyc",
    "docs/_build",
    "docs/_build/*",
    "docs/_build/html/_panels_static/panels-main.c949a650a448cc0ae9fd3441c0e17fb0.css",
    "docs/_build/html/_panels_static/panels-variables.06eb56fa6e07937060861dad626602ad.css",
    "docs/_config.yml",
    "docs/_toc.yml",
    "docs/coverage/coverage_html.js",
    "docs/coverage/favicon_32.png",
    "docs/coverage/jquery.ba-throttle-debounce.min.js",
    "docs/coverage/jquery.hotkeys.js",
    "docs/coverage/jquery.isonscreen.js",
    "docs/coverage/jquery.min.js",
    "docs/coverage/jquery.tablesorter.min.js",
    "docs/coverage/keybd_closed.png",
    "docs/coverage/keybd_open.png",
    "docs/coverage/src_schemata___init___py.html",
    "docs/coverage/src_schemata___main___py.html",
    "docs/coverage/src_schemata_apps_py.html",
    "docs/coverage/src_schemata_base_py.html",
    "docs/coverage/src_schemata_compat___init___py.html",
    "docs/coverage/src_schemata_compat_ipython_py.html",
    "docs/coverage/src_schemata_compat_ipywidgets_py.html",
    "docs/coverage/src_schemata_compat_pydantic_py.html",
    "docs/coverage/src_schemata_compat_rich_py.html",
    "docs/coverage/src_schemata_compat_typer_py.html",
    "docs/coverage/src_schemata_exceptions_py.html",
    "docs/coverage/src_schemata_forms_py.html",
    "docs/coverage/src_schemata_ipython_py.html",
    "docs/coverage/src_schemata_loaders_py.html",
    "docs/coverage/src_schemata_mediatypes_py.html",
    "docs/coverage/src_schemata_numbers_py.html",
    "docs/coverage/src_schemata_signatures_py.html",
    "docs/coverage/src_schemata_strings_py.html",
    "docs/coverage/src_schemata_tests___init___py.html",
    "docs/coverage/src_schemata_tests_conftest_py.html",
    "docs/coverage/src_schemata_tests_plugins___init___py.html",
    "docs/coverage/src_schemata_tests_plugins_anno_py.html",
    "docs/coverage/src_schemata_tests_test_types_py.html",
    "docs/coverage/src_schemata_types_py.html",
    "docs/coverage/src_schemata_ui_py.html",
    "docs/coverage/src_schemata_util_py.html",
    "docs/coverage/status.json",
    "docs/coverage/style.css",
    "docs/examples/small_program.py",
    "docs/extras/.ipynb_checkpoints/*",
    "docs/xxx.sqlite",
    "index.html",
    "jupyter_execute/docs/extras/ipython-extension.ipynb",
    "jupyter_execute/docs/extras/ipython-extension.py",
    "jupyter_execute/docs/schemata-types.ipynb",
    "jupyter_execute/docs/schemata-types.py",
    "noxfile.py",
    "pyproject.toml",
    "src/resourceful/__pycache__/*",
    "src/resourceful/__pycache__/__init__.cpython-37.pyc",
    "src/schemata/__init__.py",
    "src/schemata/__main__.py",
    "src/schemata/__pycache__/*",
    "src/schemata/__pycache__/__init__.cpython-37.pyc",
    "src/schemata/__pycache__/abc.cpython-37.pyc",
    "src/schemata/__pycache__/alias.cpython-37.pyc",
    "src/schemata/__pycache__/aliases.cpython-37.pyc",
    "src/schemata/__pycache__/app.cpython-37.pyc",
    "src/schemata/__pycache__/apps.cpython-37.pyc",
    "src/schemata/__pycache__/arrays.cpython-37.pyc",
    "src/schemata/__pycache__/base.cpython-37.pyc",
    "src/schemata/__pycache__/builtins.cpython-37.pyc",
    "src/schemata/__pycache__/caches.cpython-37.pyc",
    "src/schemata/__pycache__/callables.cpython-37.pyc",
    "src/schemata/__pycache__/complex.cpython-37.pyc",
    "src/schemata/__pycache__/composite.cpython-37.pyc",
    "src/schemata/__pycache__/context.cpython-37.pyc",
    "src/schemata/__pycache__/core.cpython-37.pyc",
    "src/schemata/__pycache__/core2.cpython-37.pyc",
    "src/schemata/__pycache__/defs.cpython-37.pyc",
    "src/schemata/__pycache__/display.cpython-37.pyc",
    "src/schemata/__pycache__/display_formatter.cpython-37.pyc",
    "src/schemata/__pycache__/displays.cpython-37.pyc",
    "src/schemata/__pycache__/dodo.cpython-37.pyc",
    "src/schemata/__pycache__/exceptions.cpython-37.pyc",
    "src/schemata/__pycache__/forms.cpython-37.pyc",
    "src/schemata/__pycache__/geo.cpython-37.pyc",
    "src/schemata/__pycache__/ipython.cpython-37.pyc",
    "src/schemata/__pycache__/jschema.cpython-37.pyc",
    "src/schemata/__pycache__/json.cpython-37.pyc",
    "src/schemata/__pycache__/ld.cpython-37.pyc",
    "src/schemata/__pycache__/lit.cpython-37.pyc",
    "src/schemata/__pycache__/literal.cpython-37.pyc",
    "src/schemata/__pycache__/mediatypes.cpython-37.pyc",
    "src/schemata/__pycache__/meta.cpython-37.pyc",
    "src/schemata/__pycache__/mixin.cpython-37.pyc",
    "src/schemata/__pycache__/mixins.cpython-37.pyc",
    "src/schemata/__pycache__/mutable.cpython-37.pyc",
    "src/schemata/__pycache__/namespace.cpython-37.pyc",
    "src/schemata/__pycache__/namespaces.cpython-37.pyc",
    "src/schemata/__pycache__/numbers.cpython-37.pyc",
    "src/schemata/__pycache__/objects.cpython-37.pyc",
    "src/schemata/__pycache__/observable.cpython-37.pyc",
    "src/schemata/__pycache__/ops.cpython-37.pyc",
    "src/schemata/__pycache__/patch.cpython-37.pyc",
    "src/schemata/__pycache__/protocols.cpython-37.pyc",
    "src/schemata/__pycache__/pytype.cpython-37.pyc",
    "src/schemata/__pycache__/pytypes.cpython-37.pyc",
    "src/schemata/__pycache__/rdfs.cpython-37.pyc",
    "src/schemata/__pycache__/resource.cpython-37.pyc",
    "src/schemata/__pycache__/schema.cpython-37.pyc",
    "src/schemata/__pycache__/signatures.cpython-37.pyc",
    "src/schemata/__pycache__/store.cpython-37.pyc",
    "src/schemata/__pycache__/strategies.cpython-37.pyc",
    "src/schemata/__pycache__/strings.cpython-37.pyc",
    "src/schemata/__pycache__/template.cpython-37.pyc",
    "src/schemata/__pycache__/tools.cpython-37.pyc",
    "src/schemata/__pycache__/trait.cpython-37.pyc",
    "src/schemata/__pycache__/traits.cpython-37.pyc",
    "src/schemata/__pycache__/translate.cpython-37.pyc",
    "src/schemata/__pycache__/types.cpython-37.pyc",
    "src/schemata/__pycache__/ui.cpython-37.pyc",
    "src/schemata/__pycache__/util.cpython-37.pyc",
    "src/schemata/__pycache__/validate.cpython-37.pyc",
    "src/schemata/__pycache__/vocab.cpython-37.pyc",
    "src/schemata/apps.py",
    "src/schemata/base.py",
    "src/schemata/compat/__init__.py",
    "src/schemata/compat/__pycache__/*",
    "src/schemata/compat/__pycache__/__init__.cpython-37.pyc",
    "src/schemata/compat/__pycache__/ipython.cpython-37.pyc",
    "src/schemata/compat/__pycache__/ipywidgets.cpython-37.pyc",
    "src/schemata/compat/__pycache__/typer.cpython-37.pyc",
    "src/schemata/compat/ipython.py",
    "src/schemata/compat/ipywidgets.py",
    "src/schemata/compat/pydantic.py",
    "src/schemata/compat/rich.py",
    "src/schemata/compat/typer.py",
    "src/schemata/exceptions.py",
    "src/schemata/mediatypes.py",
    "src/schemata/numbers.py",
    "src/schemata/readme.md",
    "src/schemata/strings.py",
    "src/schemata/tests/__init__.py",
    "src/schemata/tests/__pycache__/*",
    "src/schemata/tests/__pycache__/__init__.cpython-37.pyc",
    "src/schemata/tests/__pycache__/conftest.cpython-37-pytest-6.2.0.pyc",
    "src/schemata/tests/__pycache__/conftest.cpython-37-pytest-6.2.3.pyc",
    "src/schemata/tests/__pycache__/test_literal.cpython-37-pytest-6.2.0.pyc",
    "src/schemata/tests/__pycache__/test_literal.cpython-37.pyc",
    "src/schemata/tests/__pycache__/test_types.cpython-37-pytest-6.2.0.pyc",
    "src/schemata/tests/__pycache__/test_types.cpython-37-pytest-6.2.3.pyc",
    "src/schemata/tests/plugins/__pycache__/*",
    "src/schemata/tests/strategies.py",
    "src/schemata/tests/test_types.py",
    "src/schemata/types.py",
    "src/schemata/ui.py",
    "src/schemata/util.py",
]
execution_allow_errors = False
execution_excludepatterns = []
execution_in_temp = False
execution_timeout = 30
extensions = [
    "sphinx_togglebutton",
    "sphinx_copybutton",
    "myst_nb",
    "jupyter_book",
    "sphinxcontrib.bibtex",
    "sphinx_thebe",
    "sphinx_comments",
    "sphinx.ext.intersphinx",
    "sphinx_panels",
    "sphinx_book_theme",
]
globaltoc_path = "docs/_toc.yml"
html_add_permalinks = "¶"
html_baseurl = ""
html_favicon = ""
html_logo = ""
html_sourcelink_suffix = ""
html_theme = "sphinx_book_theme"
html_theme_options = {
    "search_bar_text": "Search this book...",
    "launch_buttons": {
        "notebook_interface": "classic",
        "binderhub_url": "https://mybinder.org",
        "jupyterhub_url": "",
        "thebe": False,
        "colab_url": "",
    },
    "path_to_docs": "",
    "repository_url": "https://github.com/deathbeds/schemata",
    "repository_branch": "master",
    "google_analytics_id": "",
    "extra_navbar": "",
    "extra_footer": "",
    "home_page_in_toc": True,
    "use_repository_button": True,
    "use_edit_page_button": True,
    "use_issues_button": True,
}
html_title = "schemata"
jupyter_cache = ""
jupyter_execute_notebooks = "auto"
language = None
latex_engine = "pdflatex"
myst_url_schemes = ["mailto", "http", "https"]
nb_output_stderr = "show"
nb_render_priority = {
    "html": [
        "application/vnd.jupyter.widget-view+json",
        "application/javascript",
        "text/html",
        "image/svg+xml",
        "image/png",
        "image/jpeg",
        "text/markdown",
        "text/latex",
        "text/plain",
    ]
}
numfig = True
panels_add_bootstrap_css = False
pygments_style = "sphinx"

bibtex_bibfiles = []
