[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core>=3.1,<4"]

[tool]
[tool.flit]
[tool.flit.metadata]
author = "tonyfast"
author-email = "tony.fast@gmail.com"
classifiers = []
home-page = "https://github.com/deathbeds/schemata.git"
keywords = ""
license = "MIT License"
maintainer = "tonyfast"
maintainer-email = "tony.fast@gmail.com"
module = "schemata"
requires = ["jsonschema", "jsonpatch", "pyld", "uritemplate"]
requires-python = ">=3.6"

[tool.flit.metadata.urls]

[tool.flit.metadata.requires-extra]
app = ["typer", "jinja2"]
web = ["fastapi", "jinja2"]
tasks = ["doit"]
ipython = ["IPython"]
test = ["pytest", "hypothesis", "hypothesis-jsonschema", "pytest-cov"]

[tool.flit.scripts]

[tool.flit.sdist]
include = []

[tool.flit.entrypoints]
