title: resourceful
author: tonyfast
copyright: '2020'
logo: ''
only_build_toc_files: true
repository: {}
execute:
  execute_notebooks: auto
exclude_patterns:
- .benchmarks/*
- .hypothesis/*
- .ipynb_checkpoints/*
- .pytest_cache/*
- .vscode/*
- __pycache__/*
- docs/.hypothesis/*
- docs/.ipynb_checkpoints/*
- docs/__pycache__/*
- docs/extras/.ipynb_checkpoints/*
- src/resourceful/__pycache__/*
- src/schemata/__pycache__/*
- src/schemata/compat/__pycache__/*
- src/schemata/tests/__pycache__/*
- src/schemata/tests/plugins/__pycache__/*
- docs/_build
- docs/_build
- docs/_build/*
html:
  favico: ''
  use_edit_page_button: false
  use_repository_button: false
  use_issues_button: false
  extra_navbar: ''
  extra_footer: ''
  google_analytics_id: ''
  home_page_in_navbar: true
  baseurl: ''
  comments:
    hypothesis: false
    utterances: false
sphinx:
  extra_extensions: []
  local_extensions: {}
  config: 
    nb_render_priority:
      html:
      - "application/vnd.jupyter.widget-view+json"
      - "application/javascript"
      - "text/html"
      - "image/svg+xml"
      - "image/png"
      - "image/jpeg"
      - "text/markdown"
      - "text/latex"
      - "text/plain"